### ISSUE TITLE
 SMTP service does not allow modification of Endpoints

### ISSUE THREAD

**Issue by supportdoxeecom** [phax/phoss-smp#155]
On the Configuration page of the various SMTPs:

https://peppol-smp-platform.doxee.com/secure/locale-en_US/menuitem-endpoints

it is not possible to modify an Endpoints once created.

Consequently, if you need to change the value of:

- Service group *:
- ID type of document *:
- Process ID *:
- Transport profile *:

you have to recreate the EndPoints from scratch

**Comment by phax** [comment]
Hi,
Yes that is correct - because of different uniqueness constraints etc. it's currently not possible to edit these 4 values.
As I know editing such an endpoint is tedious I added the copy button ![grafik](https://user-images.githubusercontent.com/196219/107409332-57197d80-6b0c-11eb-838e-fc0205ee8f34.png) with which you can create an endpoint from scratch but it is prefilled with the values of the endpoint you are copying.
If you created a new endpoint in this way, you may delete the old one afterwards.
hth, Philip
