### ISSUE TITLE
Is SML using EDELIVERY/BDMSL? There are the SML following problems when registering SMP

### ISSUE THREAD

**Issue by convicteva** [phax/phoss-smp#190]
LoggerSecurityImpl:49 - [SECURITY - CP: , Cert: null, Client-Cert: null, Admin-Pwd: null/empty/blank, SSLCert: null] null
LoggingServiceImpl:99 - eu.europa.ec.bdmsl.security.UnsecureAuthentication cannot be cast to eu.europa.ec.bdmsl.security.CertificateAuthentication
java.lang.ClassCastException: eu.europa.ec.bdmsl.security.UnsecureAuthentication cannot be cast to eu.europa.ec.bdmsl.security.CertificateAuthentication
 at eu.europa.ec.bdmsl.business.impl.ManageServiceMetadataBusinessImpl.createSMP(ManageServiceMetadataBusinessImpl.java:190) ~[classes/]
 at eu.europa.ec.bdmsl.service.impl.ManageServiceMetadataServiceImpl.create(ManageServiceMetadataServiceImpl.java:88) ~[classes/]
 at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?]

BDMSL version：4.1.0
phoss-smp ：5.4.5 」

**Comment by phax** [comment]
Hi, That seems to be a Classloader issue.
Can you try running the SMP in its own Tomcat????

**Comment by convicteva** [comment]
the smp works properly  in its own Tomcat. SML to SMP, and SML is error.

SML use https://ec.europa.eu/cefdigital/code/scm/edelivery/bdmsl.git

**Comment by phax** [comment]
Yes okay. For Peppol you don't need to use an SML.
The SML is operated centrally for Peppol.

The problem is, that both applications use generated classes with the same name. Because SML uses some "tricks" for deployment, the classloader is confused.

For the sake of simplicity, I recommend you run them in separate application servers.
