### ISSUE TITLE
Question: Service Group API when using Redirect

### ISSUE THREAD

**Issue by tmhide** [phax/phoss-smp#207]
When using Redirect, the ServiceMetadataReference for that DocumentType is not displayed in the response to the Service Group API (GET /iso6523-actorid-upis::xxxx:yyyy).
```
<smp:ServiceGroup xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:smp="http://busdox.org/serviceMetadata/publishing/1.0/" xmlns:id="http://busdox.org/transport/identifiers/1.0/">
  <id:ParticipantIdentifier scheme="iso6523-actorid-upis">xxxx:yyyy</id:ParticipantIdentifier>
  <smp:ServiceMetadataReferenceCollection/>
</smp:ServiceGroup>
```
I expect the Service Group API to return the same response regardless of whether or not Redirect is used.
Otherwise, I cannot know what DocumentType they are capable of receiving.
Is this a specification or a bug?

**Comment by phax** [comment]
@tmhide  I am reading through the specifications and the Peppol SMP spec states (chapter 4.2):
> This structure holds a list of references to SignedServiceMetadata structures. From this list, a sender can follow the references to get each SignedServiceMetadata structure.

So to my understanding, the Redirect should not be part of the list. The Redirect is primarily meant to "bridge the DNS replication gap" while data is migrated from one SMP to another. and usually does not live much longer than 24 hours.

So I will not add the "Redirect" data to the list.

**Comment by phax** [comment]
Well, usually the Participant ID is enough to find the SMP of the participant, by using the hash algorithm to create the dynamic `B-xxxxx.iso6523-actorid-upis.smldomain.org` domain names, that are a DNS alias to `smpX.publisher.smldomain.org` that are a DNS alias to `yoursmp.example.org`.

In case a participant moves to another SMP, the calculated `B-xxxxxxxx` domain name stays the same, but points to a different "publisher record" `smpY.publisher.smldomain.org` instead of `smpX.publisher.smldomain.org`. As DNS is a decentralized replicated system, some of the servers your query may not have replicated this information since the change and still redirect to `smpX.publisher.smldomain.org`. Usually the DNS subzones for Peppol need to be replicated no later then every 24 hours. And this is the only use case for which a Redirect record is needed - to bridge this "maximum 24 hours gaps" while some intermediary DNS server hasn't replicated. Okay?
