### ISSUE TITLE
Error log when registering in Peppol directory with RestAPI

### ISSUE THREAD

**Issue by sakasaka19** [phax/phoss-smp#257]
Hi Philip

Thanks for providing us with a great SMP.

When using PhossSMP's RestAPI to register Participant's information in PeppolDirectory,
I get the following error log

"JAXB [fatal_error] @ (1:77) cvc-elt.1.a: Cannot find the declaration of element 'BusinessCard'. (org.xml.sax.SAXParseException: cvc-elt.1.a: Cannot find the declaration of element 'BusinessCard'.)"
(com.helger.jaxb.validation.LoggingValidationEventHandler.onEvent(LoggingValidationEventHandler.java:54))

The registration itself succeeds, but I want to suppress the generation of error logs.
Incidentally, the error log is not output when registering via GUI.

Best regards

**Comment by phax** [comment]
Hi @sakasaka19,
Happy to hear that it works as expected :)
May I ask where exactly you get that error message? Is it when you "demo click" the `/businesscard` API or does it happen when the Directory fetches the BusinessCard from you?

**Comment by sakasaka19** [comment]
Thanks for the quick reply.
I didn't understand what a "demo click" was, so I hope the following answer is ok?

PUT /businesscard/{ServiceGroupId}

PhossSMP is throwing an error message when I register using this API.

**Comment by phax** [comment]
Ah okay - got it.
What happens is, that the SMP tries to detect the format of the Business Card to be used, because there are 3 different versions of the Business Card available. In the next update, the failed tries will not create error log messages anymore.

So please ignore this error - it works as designed.

P.S. With "demo click" I meant in the GUI via this icon:
![grafik](https://github.com/phax/phoss-smp/assets/196219/6c514938-4c83-4ede-b707-f73e5914abd3)
But it is not affected.

**Comment by sakasaka19** [comment]
I'm glad you found the cause of the problem.
I look forward to your next update.

Thank you very much.

**Comment by phax** [comment]
The necessary change was implicitly part of https://github.com/phax/phoss-smp/commit/653c01ba48ef4c39e049f0731a0a5f98d538eb9c
